### ISSUE TITLE
Static front-page

### ISSUE THREAD

**Issue by emiluzelac** [Conutant/TESSERACT#10]
Your theme supports a static front page, please make sure that when switched to something else it doesn't break the content see my screenshots. Also the sidebar goes haywire and title is out of place:

![screen shot 2015-02-09 at 11 13 25 pm](https://cloud.githubusercontent.com/assets/1784526/6121940/aeba5760-b0b1-11e4-8b2a-55f95eb6013d.png)
![screen shot 2015-02-09 at 11 13 44 pm](https://cloud.githubusercontent.com/assets/1784526/6121941/b0772baa-b0b1-11e4-9e5c-36288d68ec52.png)

http://en.support.wordpress.com/pages/front-page/ it's WPCOM, but same rule applies :)

**Comment by lunule** [comment]
Fixed.
