### ISSUE TITLE
Blog template

### ISSUE THREAD

**Issue by emiluzelac** [Conutant/TESSERACT#13]
- Titles are "dead", not clickable.
- It displays all posts, instead of what is set in Reading Settings. If "Blog pages show at most" does not work this will be an infinite number of post and eventually "kill" the browser :(

**Comment by justintadlock** [comment]
A blog page template shouldn't be needed at all.  `home.php` is the WP standard blog (posts page) template.  It'll be used on whatever page is assigned as the posts page.

**Comment by lunule** [comment]
Fixed -> I removed the blog page template, also added the translatable 'Blog' title to the top of this page, only when it's not the front page.
