### ISSUE TITLE
Right Sidebar Template

### ISSUE THREAD

**Issue by emiluzelac** [Conutant/TESSERACT#14]
Unfortunately it does not work properly.

There is an error:

```
Notice: Use of undefined constant is_active_sidebar - assumed 'is_active_sidebar' in
```

and sidebar haywire underneath :(

**Comment by justintadlock** [comment]
`is_active_sidebar` should be a function call: `is_active_sidebar()`.

**Comment by lunule** [comment]
Thanks, I've corrected this to 
`if ( ! is_active_sidebar( 'sidebar-1' ) || is_home () )`
