### ISSUE TITLE
Localizations

### ISSUE THREAD

**Issue by emiluzelac** [Conutant/TESSERACT#16]
Please make sure that all strings are localized and translatable.

Few missed examples: 
- https://github.com/Conutant/TESSERACT/blob/master/inc/customizer-frontend-functions.php#L24-L34
- https://github.com/Conutant/TESSERACT/blob/master/inc/customizer-frontend-functions.php#L42
- https://github.com/Conutant/TESSERACT/blob/master/inc/customizer-frontend-functions.php#L95-L104

**Comment by justintadlock** [comment]
Here's another:
- https://github.com/Conutant/TESSERACT/blob/master/functions.php#L228

**Comment by lunule** [comment]
Localization function __() added.
