### ISSUE TITLE
Table styles

### ISSUE THREAD

**Issue by justintadlock** [Conutant/TESSERACT#25]
Tables, while aligned correctly, could do with some borders, backgrounds, or something to distinguish between the rows and cells.  See attached image.

![tables](https://cloud.githubusercontent.com/assets/1816309/6175319/4a65b578-b2bb-11e4-9f2d-362c25321890.png)

**Comment by lunule** [comment]
Fixed - #ddd 1px solid border, and white background for th elements added.
