### ISSUE TITLE
Cite styles

### ISSUE THREAD

**Issue by justintadlock** [Conutant/TESSERACT#27]
The `<cite>` tag is practically unreadable.  It's color should be darker so that it stands out more.  See attached image.

![cite](https://cloud.githubusercontent.com/assets/1816309/6175342/7c77ba70-b2bb-11e4-9f27-5828ec1edb72.png)

**Comment by justintadlock** [comment]
Also, I should add that the `<cite>` tag is an inline element rather than block level.  This line should be removed from `style.css`: https://github.com/Conutant/TESSERACT/blob/master/style.css#L605

**Comment by lunule** [comment]
Fixed, also increased the font-size to 1.1em.
