### ISSUE TITLE
Home Page Image

### ISSUE THREAD

**Issue by Conutant** [Conutant/TESSERACT#28]
I have decided to get rid of the main homepage image (the one of the night sky) so that we don't need to include the image in the theme, so it will be easier/faster to download.  

The main images are now going to be dealt with by using plugins and not the theme itself.

**Comment by lunule** [comment]
OK, I removed the images from 'the' img folder, and the default image related line from custom-header.php

**Comment by Conutant** [comment]
Awesome, I think there might have been code in the customizer also?
