### ISSUE TITLE
Prefixing

### ISSUE THREAD

**Issue by emiluzelac** [Conutant/TESSERACT#3]
To avoid conflicts with anything that sits on top of the theme, please prefix all with unique theme-based names.

`theme_slug_`, `new_`, `tho_`, `tfo_` etc should be `tesseract_`

See: http://nacin.com/2010/05/11/in-wordpress-prefix-everything/

This is also TRT guideline.

**Comment by lunule** [comment]
prefix `tesseract_` added to theme functions ( mostly in customizer related files ).
