### ISSUE TITLE
Primary Menu & Secondary Menu

### ISSUE THREAD

**Issue by Conutant** [Conutant/TESSERACT#36]
There are two menus, primary and secondary.  The secondary should be the footer.  Right now it doesnt do anything.

**Comment by lunule** [comment]
I'm not sure I clearly understand this issue, but chances are that what you mean is not the menu but its location.

Locations are predefined and menus should be assigned to the appropriate location by the site/theme user.
If you experienced some menu configuration issue, I'll need more info about this - which menu did you try to assign which location, where do you want to display and which menu, etc.

Also I've made some code updates concerning the menu display - chances are that now it works fine. Please restest this issue, if you still experience it I'll invetigate it further as soon as I have the above mentioned more detailed info.

**Comment by lunule** [comment]
By the current settings both the header and footer menu displays, by default, the default Wordpress menu ( Sample Page ). Later the user can create as many menus as he/she wants, and can assign any of these to the header or footer.

I close this - please reopen if you have any further issues/requests concerning the default menu display.
