### ISSUE TITLE
Menu Says Open Menu / Close Menu

### ISSUE THREAD

**Issue by Conutant** [Conutant/TESSERACT#39]
When I go on mobile or on desktop and resize to mobile then hit refresh I see it says Open menu and close menu where the menu is.

**Comment by lunule** [comment]
Working on this...

**Comment by Conutant** [comment]
Is it as easy as remove these lines from header.php?

<?php _e( 'Open Menu', 'tesseract' ); ?>
<?php _e( 'Close Menu', 'tesseract' ); ?>

**Comment by lunule** [comment]
Yes. :)

I've just changed that and committed the changes.

The reason why I wasn't sure about how to handle this at first is that empty html items are not that... semantic, and there are a lot of valid and semantic HTML guidelines out there suggesting different workarounds to solve similar questions. Also users reading with screenreaders might have difficulties with such elements.

I think the removal is completely OK for the moment - then later, if you get feedbacks from users claiming about not semantic code ( which has a probability near to 0 ), another issue can be opened for that.

**Comment by Conutant** [comment]
Perfect!  Thanks!
