### ISSUE TITLE
Blog Page Template

### ISSUE THREAD

**Issue by Conutant** [Conutant/TESSERACT#43]
If I edit the page and set the template to Blog it is a different style then if I go to Settings -> reading and set it there.  Can we delete the blog page template and just be able to set it to settings -> reading?

**Comment by Conutant** [comment]
But I really think I like the blog page template that you choose when you edit the page better than the one when you go to settings reading.  One displays images and the other does not, so I think the one the displays the featured images is better than the one that doesn't.

**Comment by lunule** [comment]
Tyler, that's probably my mistake, somehow my removal of the blog page template has not been committed. Now this is 'recommitted' in the dev_gabor branch.

I've decided to remove it based on Justin's comment in issue 13 @ https://github.com/Conutant/TESSERACT/issues/13

Please update this issue if you still need this template and I'll check what style updates are necessary.
