### ISSUE TITLE
Primary and Secondary Menu

### ISSUE THREAD

**Issue by Conutant** [Conutant/TESSERACT#46]
The primary menu should be the header menu and the secondary should be the footer menu.

**Comment by lunule** [comment]
This can not be predefined this way - when the user installs the theme, he has only menu locations ( Primary menu and Secondary menu ) but not menus. Once the user creates at least one menu, he can assign it to one of these locations.

What we can do here is to rename the locations themselves to 'Header' and 'Footer'. This way the function of locations might be more obvious to the user. 

For the moment I implement this version and commit the update to the dev_gabor branch. Please update this ticket if you need some other change here and this recent commit needs to be revoked.

**Comment by Conutant** [comment]
When I go to appearance > menu and set the menu to primary and secondary it does not go to the header and footer. I have to set it in the cuomstizer, I was just wondering if I could set it in the dashboard under appearance > menu instead

**Comment by lunule** [comment]
Thanks for the explication - well yes, in this situation there's a conflict between the built-in/default menu->location registration method and the theme options.

What you'd like to achieve is technically possible, however, based on the information available on the official WP mailing lists the menu settings will be integrated into the customizer, and this update will be implemented in a few weeks or months. AND as soon as this implementation is available the theme's current option to set menu locations become redundant and confusing.

So we have two options here:
1. I can implement the synchronization of the two different section for menu->location registration - then once WP gets the above described updated customizer, we can simply remove the related and similar Tesseract settings;
2. Knowing about the above described future updates it's worth to consider completely removing this feature from Tesseract's own customizer settings.

I'm looking forward to your feedback about how to handle this.

**Comment by Conutant** [comment]
Let's just wait for wordpress to do their update before we do anything.   Then we will remove it from the tesseract options.  It is just confusing because if I go to appearance > menu and create a new menu then under theme location I set it to the "header" and create another menu and set the theme location to the "footer" it does not show up on my homepage.

**Comment by Conutant** [comment]
![screen shot 2015-03-16 at 4 32 14 pm](https://cloud.githubusercontent.com/assets/6529689/6678664/b9617e78-cbfa-11e4-8a63-043f95880365.png)

**Comment by lunule** [comment]
Fixed.
