### ISSUE TITLE
Post featured image position

### ISSUE THREAD

**Issue by lunule** [Conutant/TESSERACT#49]
I've found this new one while investigating issue#46 - if you take a look at http://screencast.com/t/GoVTbSmeR7 you can see that the featured image has a wrong position. For some reason there's a -60px top margin defined for it.

I wasn't sure about your original intent concerning the right post featured image position thus the opening of this issue - could you update this with a few line about the right positioning? Should there be some blank between the header and the top of the featured image? Is the width OK or do you have an intention of using full width featured images?... etc, etc, every bit of info about feat. img handling might come in handy here...

**Comment by Conutant** [comment]
Good catch!!  I was trying to go for this look, and it works on most browsers but not on safari and whatever you are on.  I didn't check all browsers yet.  

Could you make it work?

Thanks!

![screen shot 2015-03-17 at 9 54 11 pm](https://cloud.githubusercontent.com/assets/6529689/6702967/fa6a18f2-ccf0-11e4-99af-487885a74f4f.png)

**Comment by Conutant** [comment]
Weird, this works in safari just fine:  http://tyler.com/2015/create-a-wordpress-website-2015/  it must have been an update that was made.  Might be easy to compare the differences in the code and modify it.

**Comment by Conutant** [comment]
Actually it is only on your branch that it is not right.  If you download the master branch and refresh it works fine.  Can you update your code to reflect what is in the master branch updates?

**Comment by lunule** [comment]
OH COOL!!! - Thanks, based on your screenshot I've found out where's this difference. It was one line in the style.css of the dev_gabor branch.
Fixed.

**Comment by Conutant** [comment]
awesome!
