### ISSUE TITLE
Customizer - Footer options

### ISSUE THREAD

**Issue by emiluzelac** [Conutant/TESSERACT#9]
The only option that I could get to work is the first, which is default (nothing), the rest  Logo, Social Icons, Search Bar doesn't do anything. It works only if this is selected: Display a horizontal footer menu. This will cause issues with your users. Once Display a horizontal footer menu is selected, the radio buttons listed above should show, otherwise it becomes pretty useless.

**Comment by lunule** [comment]
Yeah, the logics of this block needs some improvement - just working on it...

**Comment by emiluzelac** [comment]
Great 👍

**Comment by lunule** [comment]
Fixed.
